package taskqueue

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// AgentsFileName is the guide `tq init` keeps inside the task directory, and
// the file it points at from the repository's own agent instructions.
const AgentsFileName = "AGENTS.md"

const generatedNotice = "<!-- Generated by `tq init`. Edits are overwritten. -->"

// SyncAgentsDocs writes the guide that lives beside the tasks and returns the
// files it wrote, so the CLI can say what changed. It rewrites nothing that is
// already right.
//
// It deliberately does not touch the repository's own AGENTS.md or CLAUDE.md.
// Editing a document tq did not author means parsing arbitrary Markdown, and
// every safe-looking way to do that found another way to damage a committed
// file. Pointing an agent at the guide is one line a person writes once; tq
// prints it instead.
func SyncAgentsDocs(store *Store) ([]string, error) {
	guide := filepath.Join(store.Dir, AgentsFileName)
	changed, err := writeIfChanged(guide, taskGuide(store.Dir))
	if err != nil {
		return nil, err
	}
	if !changed {
		return nil, nil
	}
	return []string{guide}, nil
}

// GuidePointer is the line to add to an agent instructions file so the guide
// is loaded with it. The path is relative to the repository root, where such a
// file conventionally sits, falling back to the directory holding the task
// directory and then to an absolute path.
func GuidePointer(store *Store) string {
	guide := filepath.Join(store.Dir, AgentsFileName)

	from := filepath.Dir(store.Dir)
	if root, ok := repositoryRoot(store.Dir); ok {
		from = root
	}
	if rel, err := filepath.Rel(from, guide); err == nil {
		return "@" + filepath.ToSlash(rel)
	}
	return "@" + filepath.ToSlash(guide)
}

func writeIfChanged(path string, content []byte) (bool, error) {
	if existing, err := os.ReadFile(path); err == nil && string(existing) == string(content) {
		return false, nil
	} else if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	if err := writeAtomic(path, content); err != nil {
		return false, err
	}
	return true, nil
}

// writeAtomic replaces a file in one step, the way Store.write does for task
// files. These are documents tq did not author, so a truncating write that
// fails halfway would leave a person's instructions destroyed.
func writeAtomic(path string, content []byte) (err error) {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".tq-*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer func() {
		if err != nil { // leave nothing behind when the write failed
			_ = tmp.Close()
			_ = os.Remove(tmpName)
		}
	}()

	if _, err = tmp.Write(content); err != nil {
		return err
	}
	if err = tmp.Chmod(0o644); err != nil {
		return err
	}
	if err = tmp.Sync(); err != nil {
		return err
	}
	if err = tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

// taskGuide is the agent-facing cheat sheet stored next to the tasks. It is
// generated so it cannot drift from the statuses, priorities and exit codes the
// binary actually implements.
func taskGuide(taskDir string) []byte {
	return fmt.Appendf(nil, `%s

# Task queue

This directory is a `+"`tq`"+` task queue: one Markdown file per task, named
`+"`<id>-<title-slug>.md`"+`, with YAML frontmatter. The files are the source of
truth and are meant to be committed.

Use the CLI rather than editing files by hand — it validates, keeps timestamps
and filenames in sync, and writes atomically. Every command below works from any
subdirectory of the repository.

## Working a task

Claim a task before the first edit and close it before you report the work
done. These are steps in the task, not bookkeeping around it.

1. `+"`tq ready --json`"+` — the tasks that are unblocked and unclaimed.
2. `+"`tq show <id> --json`"+` — read it in full, body included.
3. `+"`tq move <id> in-progress`"+` — claim it, before you touch a file.
4. `+"`tq note <id> \"what happened\"`"+` — append a timestamped note as you go:
   decisions, surprises, anything the next reader would need. A note keeps the
   line breaks you give it, so it can hold a paragraph or a short list.
5. `+"`tq done <id>`"+` — close it once the work is verified.

Use `+"`tq move <id> <status>`"+` for any other transition.

## Find things

    tq list --json                  every task
    tq list --status todo --label backend --priority high --assignee agent-api
    ls %s | grep auth               filenames carry a slug of the title
    grep -ril "oidc" %s             full-text search across tasks

## Create and change

    tq add "Title" --priority high --label backend --depends-on TQ-0002 --body "…"
    tq update <id> --title "New title" --assignee agent-api
    tq update <id> --add-label auth --remove-label backend
    tq update <id> --add-dependency TQ-0002 --remove-dependency TQ-0003

Arguments starting with "-" go after "--": tq note <id> -- "-1 test failing".

## Rules of the format

- Statuses: %s
- Priorities: %s (default: %s)
- Notes are the last section of a body, introduced by a `+"`---`"+` rule with a blank
  line above it. A `+"`## Notes`"+` heading anywhere else is ordinary content, so a
  body can document notes without `+"`tq note`"+` mistaking prose for notes.
- Each note is one Markdown list item. The lines after its first are indented
  under the bullet, which is what keeps a multi-line note inside its note.
- A task is *ready* when it is neither done nor in-progress and every task in
  `+"`depends_on`"+` exists and is done. A missing dependency blocks it.
- `+"`--json`"+` prints JSON to stdout and nothing else; errors go to stderr.
- Exit codes: 0 success, 1 validation error, 2 task not found, 3 task directory
  missing and uncreatable.

## Where the tasks live

    %s

Set `+"`%s`"+` to point tq at a different task directory. The search for one
walks up from the working directory and stops at the repository root, so a
queue above the project does not capture it. Set `+"`%s=true`"+` to let
it walk on to the filesystem root.
`,
		generatedNotice,
		filepath.Base(taskDir), filepath.Base(taskDir),
		strings.Join(Statuses, ", "),
		strings.Join(Priorities, ", "), PriorityNormal,
		taskDir,
		EnvTaskDir, EnvWalkForever,
	)
}
