package main

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// AgentsFileName is the guide `tq init` keeps inside the task directory, and
// the file it points at from the repository's own agent instructions.
const AgentsFileName = "AGENTS.md"

// rootDocNames are the repository-level agent instruction files that get a
// pointer to the task guide. The first one is created when none exists.
var rootDocNames = []string{"AGENTS.md", "CLAUDE.md"}

const (
	taskSectionTitle = "Task management"
	generatedNotice  = "<!-- Generated by `tq init`. Edits are overwritten. -->"
)

// SyncAgentsDocs writes the task-directory guide and makes sure the
// repository's agent instructions point at it. workingDir is where the command
// was run, which is what locates the project when it is not a Git repository.
// It returns the files it wrote, so the CLI can say what changed, and rewrites
// nothing that is already right.
func SyncAgentsDocs(store *Store, workingDir string) ([]string, error) {
	root := docRoot(workingDir)

	link, err := filepath.Rel(root, filepath.Join(store.Dir, AgentsFileName))
	if err != nil {
		// Different volumes, say: an absolute path still works as a link.
		link = filepath.Join(store.Dir, AgentsFileName)
	}
	link = filepath.ToSlash(link)

	var written []string

	guide := filepath.Join(store.Dir, AgentsFileName)
	changed, err := writeIfChanged(guide, taskGuide(store.Dir))
	if err != nil {
		return nil, err
	}
	if changed {
		written = append(written, guide)
	}

	for _, name := range rootDocNames {
		path := filepath.Join(root, name)
		if sameFile(path, guide) {
			// The task directory is the doc root, so this file is the guide
			// itself. A document cannot point at itself: appending the section
			// would bury the guide under it, and the next run would strip the
			// section and append it again, forever.
			continue
		}

		existing, err := os.ReadFile(path)
		if err != nil {
			if !os.IsNotExist(err) {
				return nil, err
			}
			continue // only files that already exist are updated
		}

		updated, ok := withTaskSection(string(existing), link)
		if !ok {
			continue
		}
		if _, err := writeIfChanged(path, []byte(updated)); err != nil {
			return nil, err
		}
		written = append(written, path)
	}

	// Nothing to point from yet: start the conventional file.
	if !containsAnyRootDoc(root) {
		path := filepath.Join(root, rootDocNames[0])
		content, _ := withTaskSection("", link)
		if _, err := writeIfChanged(path, []byte(content)); err != nil {
			return nil, err
		}
		written = append(written, path)
	}

	return written, nil
}

// docRoot is where the repository's agent instructions live: the root of the
// enclosing Git repository, falling back to the directory the command ran in.
func docRoot(workingDir string) string {
	dir, err := filepath.Abs(workingDir)
	if err != nil {
		dir = workingDir
	}
	if root, ok := repositoryRoot(dir); ok {
		return root
	}
	return dir
}

func containsAnyRootDoc(root string) bool {
	for _, name := range rootDocNames {
		if _, err := os.Stat(filepath.Join(root, name)); err == nil {
			return true
		}
	}
	return false
}

// sameFile reports whether two paths lead to the same file. One of them comes
// from TQ_DIR and the other from the repository root, so they can differ as
// strings and still name one file — through a symlink, or on a
// case-insensitive filesystem. Paths that cannot be stat'ed are compared
// literally, which is all that is left to go on.
func sameFile(a, b string) bool {
	infoA, errA := os.Stat(a)
	infoB, errB := os.Stat(b)
	if errA == nil && errB == nil {
		return os.SameFile(infoA, infoB)
	}
	if errA == nil || errB == nil {
		return false // one exists and the other does not
	}
	absA, errA := filepath.Abs(a)
	absB, errB := filepath.Abs(b)
	return errA == nil && errB == nil && absA == absB
}

func writeIfChanged(path string, content []byte) (bool, error) {
	if existing, err := os.ReadFile(path); err == nil && string(existing) == string(content) {
		return false, nil
	} else if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return false, err
	}
	return true, nil
}

// withTaskSection returns doc with a "Task management" section pointing at
// link, and reports whether anything needed changing. An existing section is
// rewritten (the task directory may have moved); a section that already points
// at the guide is left alone.
func withTaskSection(doc, link string) (string, bool) {
	section := fmt.Sprintf("See [%s](%s)", AgentsFileName, link)

	lines := strings.Split(strings.TrimRight(doc, "\n"), "\n")
	levels := headingLevels(lines)

	if start, end, level := findSection(lines, levels, taskSectionTitle); start >= 0 {
		if pointsAtGuide(lines[start:end], levels[start:end], link) {
			return doc, false
		}
		replacement := append([]string{strings.Repeat("#", level) + " " + taskSectionTitle, "", section}, lines[end:]...)
		return strings.Join(append(lines[:start], replacement...), "\n") + "\n", true
	}

	// A second level-one heading would be invalid in a document that already
	// has one, so match the depth of what is already there.
	heading := "# "
	if slices.Contains(levels, 1) {
		heading = "## "
	}

	if doc = strings.TrimRight(doc, "\n"); doc == "" {
		return heading + taskSectionTitle + "\n\n" + section + "\n", true
	}
	return doc + "\n\n" + heading + taskSectionTitle + "\n\n" + section + "\n", true
}

// pointsAtGuide reports whether a section already sends the reader to the
// guide, either as a Markdown link or as an `@`-include. A mention inside a
// fenced block documents the convention instead of following it, so it does
// not count.
func pointsAtGuide(lines []string, levels []int, link string) bool {
	for i, line := range lines {
		if levels[i] == fencedLine {
			continue
		}
		if strings.Contains(line, "("+link+")") || strings.Contains(line, "@"+link) {
			return true
		}
	}
	return false
}

// findSection locates a heading by title and returns the line range it covers
// (up to the next heading of the same or higher level) plus its level. levels
// comes from headingLevels, so headings quoted inside a fence are ignored.
func findSection(lines []string, levels []int, title string) (start, end, level int) {
	for i, line := range lines {
		hashes := levels[i]
		if hashes <= 0 || !strings.EqualFold(strings.TrimSpace(line[hashes:]), title) {
			continue
		}

		for j := i + 1; j < len(lines); j++ {
			if depth := levels[j]; depth > 0 && depth <= hashes {
				return i, j, hashes
			}
		}
		return i, len(lines), hashes
	}
	return -1, -1, 0
}

// fencedLine marks a line that sits inside a fenced code block, delimiters
// included. Such a line is never structure: a leading `#` there is a shell
// comment, and a link is an example.
const fencedLine = -1

// headingLevels classifies every line of a document: the level of its ATX
// heading, 0 for anything else, and fencedLine inside a fenced code block.
func headingLevels(lines []string) []int {
	if levels, balanced := scanHeadingLevels(lines, true); balanced {
		return levels
	}
	// The document has an unclosed (or mismatched) fence, which would hide
	// every line below it — including a real Task management section, so that
	// syncing would append a second one on every run and grow a committed file
	// without bound. Read the fences as ordinary lines instead, the way
	// notesStart does for a task body.
	levels, _ := scanHeadingLevels(lines, false)
	return levels
}

func scanHeadingLevels(lines []string, honourFences bool) (levels []int, balanced bool) {
	levels = make([]int, len(lines))
	open := ""

	for i, line := range lines {
		if !honourFences {
			levels[i] = headingLevel(line)
			continue
		}
		fence, info := fenceDelimiter(line)
		if open != "" {
			levels[i] = fencedLine
			// A closing fence is at least as long as its opener, uses the same
			// character and carries no info string.
			if fence != "" && fence[0] == open[0] && len(fence) >= len(open) && strings.TrimSpace(info) == "" {
				open = ""
			}
			continue
		}
		// A backtick in the info string means a run of inline code, not a fence.
		if fence != "" && (fence[0] == '~' || !strings.Contains(info, "`")) {
			open, levels[i] = fence, fencedLine
			continue
		}
		levels[i] = headingLevel(line)
	}
	return levels, open == ""
}

// headingLevel returns the level of an ATX heading, or 0 when the line is not
// one. A heading starts at column 0 and its hashes are followed by a space.
func headingLevel(line string) int {
	hashes := len(line) - len(strings.TrimLeft(line, "#"))
	if hashes == 0 || hashes > 6 {
		return 0
	}
	if rest := line[hashes:]; rest != "" && !strings.HasPrefix(rest, " ") {
		return 0
	}
	return hashes
}

// indentColumns measures leading whitespace the way Markdown does, with tabs
// advancing to the next four-column stop. One leading tab is therefore already
// four columns, which is why a tab-indented fence is an indented code block.
func indentColumns(indent string) int {
	columns := 0
	for _, r := range indent {
		if r == '\t' {
			columns += 4 - columns%4
		} else {
			columns++
		}
	}
	return columns
}

// fenceDelimiter splits a code fence line into its run of backticks or tildes
// and the info string that follows. It returns an empty marker for any other
// line, indented code blocks included.
func fenceDelimiter(line string) (fence, info string) {
	trimmed := strings.TrimLeft(line, " \t")
	if indentColumns(line[:len(line)-len(trimmed)]) > 3 {
		return "", "" // indented four columns: a code block, not a fence
	}
	for _, char := range "`~" {
		if run := len(trimmed) - len(strings.TrimLeft(trimmed, string(char))); run >= 3 {
			return trimmed[:run], trimmed[run:]
		}
	}
	return "", ""
}

// taskGuide is the agent-facing cheat sheet stored next to the tasks. It is
// generated so it cannot drift from the statuses, priorities and exit codes the
// binary actually implements.
func taskGuide(taskDir string) []byte {
	return fmt.Appendf(nil, `%s

# Task queue

This directory is a `+"`tq`"+` task queue: one Markdown file per task, named
`+"`<id>-<title-slug>.md`"+`, with YAML frontmatter. The files are the source of
truth and are meant to be committed.

Use the CLI rather than editing files by hand — it validates, keeps timestamps
and filenames in sync, and writes atomically. Every command below works from any
subdirectory of the repository.

## Working a task

Claim a task before the first edit and close it before you report the work
done. These are steps in the task, not bookkeeping around it.

1. `+"`tq ready --json`"+` — the tasks that are unblocked and unclaimed.
2. `+"`tq show <id> --json`"+` — read it in full, body included.
3. `+"`tq move <id> in-progress`"+` — claim it, before you touch a file.
4. `+"`tq note <id> \"what happened\"`"+` — append a timestamped note as you go:
   decisions, surprises, anything the next reader would need. A note keeps the
   line breaks you give it, so it can hold a paragraph or a short list.
5. `+"`tq done <id>`"+` — close it once the work is verified.

Use `+"`tq move <id> <status>`"+` for any other transition.

## Find things

    tq list --json                  every task
    tq list --status todo --label backend --priority high --assignee agent-api
    ls %s | grep auth               filenames carry a slug of the title
    grep -ril "oidc" %s             full-text search across tasks

## Create and change

    tq add "Title" --priority high --label backend --depends-on TQ-0002 --body "…"
    tq update <id> --title "New title" --assignee agent-api
    tq update <id> --add-label auth --remove-label backend
    tq update <id> --add-dependency TQ-0002 --remove-dependency TQ-0003

Arguments starting with "-" go after "--": tq note <id> -- "-1 test failing".

## Rules of the format

- Statuses: %s
- Priorities: %s (default: %s)
- Notes are the last section of a body, introduced by a `+"`---`"+` rule with a blank
  line above it. A `+"`## Notes`"+` heading anywhere else is ordinary content, so a
  body can document notes without `+"`tq note`"+` mistaking prose for notes.
- Each note is one Markdown list item. The lines after its first are indented
  under the bullet, which is what keeps a multi-line note inside its note.
- A task is *ready* when it is neither done nor in-progress and every task in
  `+"`depends_on`"+` exists and is done. A missing dependency blocks it.
- `+"`--json`"+` prints JSON to stdout and nothing else; errors go to stderr.
- Exit codes: 0 success, 1 validation error, 2 task not found, 3 task directory
  missing and uncreatable.

## Where the tasks live

    %s

Set `+"`%s`"+` to point tq at a different task directory.
`,
		generatedNotice,
		filepath.Base(taskDir), filepath.Base(taskDir),
		strings.Join(Statuses, ", "),
		strings.Join(Priorities, ", "), PriorityNormal,
		taskDir,
		EnvTaskDir,
	)
}
