package guide

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/fmartingr/taskqueue/internal/task"

	"github.com/fmartingr/taskqueue/internal/fsx"

	"github.com/fmartingr/taskqueue/internal/config"

	"github.com/fmartingr/taskqueue/internal/store"
)

// AgentsFileName is the guide `tq init` keeps inside the task directory, and
// the file a project's own agent instructions reference.
const AgentsFileName = "AGENTS.md"

const generatedNotice = "<!-- Generated by `tq init`. Edits are overwritten. -->"

// SyncAgentsDocs writes the guide that lives beside the tasks and returns the
// files it wrote, so the CLI can say what changed. It rewrites nothing that is
// already right.
//
// It deliberately does not touch the repository's own AGENTS.md or CLAUDE.md.
// Editing a document tq did not author means parsing arbitrary Markdown, and
// every safe-looking way to do that found another way to damage a committed
// file. Pointing an agent at the guide is one line a person writes once, in the
// file of their choosing; tq prints where the guide is and leaves it to them.
func SyncAgentsDocs(st *store.Store) ([]string, error) {
	// The guide prints the priority vocabulary to agents, so it has to print
	// the project's own or it becomes a lie the moment one is declared.
	priorities, err := st.Priorities()
	if err != nil {
		return nil, err
	}
	columns, err := st.Columns()
	if err != nil {
		return nil, err
	}

	guide := filepath.Join(st.Dir, AgentsFileName)
	changed, err := writeIfChanged(guide, taskGuide(st.Dir, priorities, columns))
	if err != nil {
		return nil, err
	}
	if !changed {
		return nil, nil
	}
	return []string{guide}, nil
}

// GuidePath is the guide's location, for the CLI to name once init has written
// it. It is absolute: the file a user references it from is theirs to choose,
// and no directory this package could pick — the repository root, the parent of
// the task directory, the working directory — is the one that file sits in. A
// relative path would be correct from exactly one of them and silently wrong
// everywhere else (TQ-0061).
func GuidePath(st *store.Store) string {
	guide := filepath.Join(st.Dir, AgentsFileName)
	if abs, err := filepath.Abs(guide); err == nil {
		return abs
	}
	return filepath.Clean(guide)
}

func writeIfChanged(path string, content []byte) (bool, error) {
	if existing, err := os.ReadFile(path); err == nil && string(existing) == string(content) {
		return false, nil
	} else if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	if err := fsx.WriteAtomic(path, content); err != nil {
		return false, err
	}
	return true, nil
}

// offering is the columns `tq ready` hands work out of, for the guide.
func offering(columns task.Columns) []string {
	var out []string
	for _, name := range columns.Names() {
		if columns.Offers(name) {
			out = append(out, name)
		}
	}
	if len(out) == 0 {
		return []string{"no column"}
	}
	return out
}

// satisfying is the column a dependency has to reach to count as met, or a
// phrase saying the project has not settled on one.
func satisfying(columns task.Columns) string {
	name, err := columns.SatisfyingColumn()
	if err != nil {
		return "no column this project has agreed on"
	}
	return name
}

// taskGuide is the agent-facing cheat sheet stored next to the tasks. It is
// generated so it cannot drift from the statuses, priorities and exit codes the
// binary actually implements.
func taskGuide(taskDir string, priorities task.Priorities, columns task.Columns) []byte {
	// The examples set a priority too, so they have to name one the project
	// actually has: `tq add --priority high` is as much a lie as the list would
	// be. The most severe is always there — Names falls back to the built-in
	// set, and the config loader refuses an empty one.
	example := priorities.Names()[0]

	return fmt.Appendf(nil, `%s

# Task queue

This directory is a `+"`tq`"+` task queue: one Markdown file per task, named
`+"`<id>-<title-slug>.md`"+`, with YAML frontmatter. The files are the source of
truth and are meant to be committed.

Use the CLI rather than editing these files by hand. The frontmatter is the
CLI's: it allocates the IDs, checks the statuses and the priorities against the
project's, keeps the timestamps and the filename in sync with what it wrote, and
writes atomically. The body is yours to rewrite, and `+"`tq update <id> --body`"+`
is how — it replaces the content and keeps the notes. Every
command below works from any subdirectory of the project — every command but
`+"`tq init`"+`, which creates a queue wherever it is run, so run it once at the
project root and never below it.

## Working a task

Claim a task before the first edit and close it before you report the work
done. These are steps in the task, not bookkeeping around it.

1. `+"`tq ready --json`"+` — the tasks that are unblocked and unclaimed.
2. `+"`tq show <id> --json`"+` — read it in full, body included.
3. `+"`tq move <id> in-progress`"+` — claim it, before you touch a file.
4. `+"`tq note <id> \"what happened\"`"+` — append a timestamped note as you go:
   decisions, surprises, anything the next reader would need. A note keeps the
   line breaks you give it, so it can hold a paragraph or a short list.
5. `+"`tq done <id>`"+` — close it once the work is verified.

Use `+"`tq move <id> <status>`"+` for any other transition.

## Find things

    tq list --json                  every task
    tq list --status todo --label backend --priority %s --assignee agent-api
    ls %s | grep auth               filenames carry a slug of the title
    grep -ril "oidc" %s             full-text search across tasks

## Create and change

    tq add "Title" --priority %s --label backend --depends-on TQ-0002 --body "…"

A task filed this way lands in the board's default column, which may not
be one `+"`tq ready`"+` offers — see Statuses below.
`+"`tq move <id> <status>`"+` is what puts it in the queue.
    tq update <id> --title "New title" --assignee agent-api
    tq update <id> --add-label auth --remove-label backend
    tq update <id> --add-dependency TQ-0002 --remove-dependency TQ-0003

Rewrite a body — correcting a finding, re-scoping a fix — with `+"`--body`"+`. The
notes on the task are kept, so the record of how it got here survives the edit,
and a notes section in the text you pass is ignored: the body `+"`tq show`"+`
hands you can be edited and handed straight back without doubling the record.
`+"`tq note`"+` is still the only way to add to it. A body is a document, so pass
it on stdin rather than fighting a shell over the quoting:

    tq update <id> --body - <<'EOF'
    ## Finding

    …
    EOF

Arguments starting with "-" go after "--": tq note <id> -- "-1 test failing".

## Labels

Labels are freeform — `+"`--label`"+` takes any string — but the project declares a
vocabulary in `+"`%s`"+`, and that is the shared one: it is what
gives a label its colour and display name on the board, and what groups it
under the part before a `+"`/`"+`. Prefer a label already in the set. A new one is
accepted everywhere and simply renders neutral, and it shows up as
unconfigured below, so it can be adopted into the set or cleaned up.

    tq label list                   the vocabulary, and what each label is on
    tq label list --json            the same, for an agent

The `+"`/`"+` groups labels for display only. A label is stored and matched as the
whole string, so `+"`tq list --label component/backend`"+` takes the whole key.

## Rules of the format

- Statuses: %s.
  The board, left to right, declared by the project in `+"`%s`"+`: a
  status outside it is refused on write. A task filed without one lands in
  %s. `+"`tq ready`"+` offers work from %s, and a dependency counts as met
  once it reaches %s.
- Priorities: %s (default: %s).
  Most severe first, and that order is the sort order. Unlike labels this is a
  closed set, declared by the project in `+"`%s`"+`: a value outside it
  is refused on write.
- Notes are the last section of a body, introduced by a `+"`---`"+` rule with a blank
  line above it. A `+"`## Notes`"+` heading anywhere else is ordinary content, so a
  body can document notes without `+"`tq note`"+` mistaking prose for notes.
- Each note is one Markdown list item. The lines after its first are indented
  under the bullet, which is what keeps a multi-line note inside its note.
- The filename carries a slug of the title, but the `+"`id`"+` in the frontmatter is
  what identifies a task. `+"`tq update --title`"+` renames the file itself; never
  rename one by hand to match a new title, and look a task up by its ID rather
  than by rebuilding a filename out of one.
- A task is *ready* when it is neither done nor in-progress and every task in
  `+"`depends_on`"+` exists and is done. A missing dependency blocks it.
- IDs are sequential but not contiguous. A number a task still lists in
  `+"`depends_on`"+` is never handed to a new task, so removing a file by hand —
  an `+"`rm`"+`, a revert, a merge — leaves a gap rather than a number the next
  `+"`tq add`"+` recycles into every dependency that pointed at the task that
  went. The gap is not something to fix, and the dependency stays missing,
  which is what keeps the dependent blocked.
- `+"`--json`"+` prints JSON to stdout and nothing else; errors go to stderr.
- A task file's extension is a lowercase `+"`.md`"+`, and only that. A file named
  `+"`TQ-0001-fix-bug.MD`"+` is not a task file: tq does not read it, list it,
  adopt its ID or rename it. It is named on stderr like a file that will not
  parse, and renaming it is yours to do — tq never touches a path it does not
  own.
- A file this directory holds that cannot be parsed — a merge conflict, a key
  the format does not have — is skipped rather than failing the listing.
  `+"`tq list`"+` and `+"`tq ready`"+` still exit 0 and print what they could
  read, and name each skipped file on stderr. The queue is that many tasks
  short until the file is fixed, so fix it rather than reading past the warning.
- A listing is checked against the directory before it is printed, so a task
  another process is retitling is not quietly missing from it, or in it twice.
  When the directory will not hold still, the command says so on stderr and
  still exits 0: run it again rather than planning against what it printed.
- Exit codes: 0 success, 1 validation error, 2 task not found, 3 no task queue
  found — run `+"`tq init`"+`.

## Where the tasks live

    %s

The project marker is `+"`%s`"+`, and it says where the tasks live:

    version: 1
    path: .tasks

`+"`path`"+` is resolved against the directory holding that file. The marker is
the only thing tq looks for: a directory merely named .tasks is not a queue.

Two rules, and nothing else:

- `+"`tq init`"+` creates the queue in the directory it is run in — the marker,
  the task directory and this guide — and nowhere else. It never searches, never
  adopts a project above, never relocates to a repository root.
- Every other command walks up from the current directory for the marker,
  stopping at the home directory, and uses the nearest one — or running to the
  filesystem root, from a directory outside the home directory. With no marker
  it exits 3 and says to run `+"`tq init`"+`. No command creates a queue on its
  own.

Once a command has found the marker, that file is the whole answer: the board,
the priorities, the labels, and where the tasks are. Nothing goes the other way,
so a `+"`path`"+` pointing outside the marker's own directory keeps all of it.

Set `+"`%s`"+` to hand tq its marker instead of having it walk for one, for
every command, `+"`tq init`"+` included. It names a `+"`%s`"+` file, not
a directory, and the tasks are wherever that marker's `+"`path`"+` says — so a
command run under it works on that whole project, from any directory. A file it
names that is missing, is a directory, or will not parse is an error.
`,
		generatedNotice,
		example,
		filepath.Base(taskDir), filepath.Base(taskDir),
		example,
		config.ConfigFileName,
		strings.Join(columns.Names(), ", "), config.ConfigFileName,
		columns.Default(),
		strings.Join(offering(columns), " and "), satisfying(columns),
		strings.Join(priorities.Names(), ", "), priorities.Default(), config.ConfigFileName,
		taskDir,
		config.ConfigFileName, config.EnvConfigPath, config.ConfigFileName,
	)
}
