package guide

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/fmartingr/taskqueue/internal/task"

	"github.com/fmartingr/taskqueue/internal/fsx"

	"github.com/fmartingr/taskqueue/internal/config"

	"github.com/fmartingr/taskqueue/internal/store"
)

// AgentsFileName is the guide `tq init` keeps inside the task directory, and
// the file a project's own agent instructions reference.
const AgentsFileName = "AGENTS.md"

const generatedNotice = "<!-- Generated by `tq init`. Edits are overwritten. -->"

// SyncAgentsDocs writes the guide that lives beside the tasks and returns the
// files it wrote, so the CLI can say what changed. It rewrites nothing that is
// already right.
//
// It deliberately does not touch the repository's own AGENTS.md or CLAUDE.md.
// Editing a document tq did not author means parsing arbitrary Markdown, and
// every safe-looking way to do that found another way to damage a committed
// file. Pointing an agent at the guide is one line a person writes once, in the
// file of their choosing; tq prints where the guide is and leaves it to them.
func SyncAgentsDocs(st *store.Store) ([]string, error) {
	// The guide prints the priority vocabulary to agents, so it has to print
	// the project's own or it becomes a lie the moment one is declared.
	priorities, err := st.Priorities()
	if err != nil {
		return nil, err
	}
	columns, err := st.Columns()
	if err != nil {
		return nil, err
	}

	guide := filepath.Join(st.Dir, AgentsFileName)
	changed, err := writeIfChanged(guide, taskGuide(st.Dir, priorities, columns))
	if err != nil {
		return nil, err
	}
	if !changed {
		return nil, nil
	}
	return []string{guide}, nil
}

// GuidePath is the guide's location, for the CLI to name once init has written
// it. It is absolute: the file a user references it from is theirs to choose,
// and no directory this package could pick — the repository root, the parent of
// the task directory, the working directory — is the one that file sits in. A
// relative path would be correct from exactly one of them and silently wrong
// everywhere else (TQ-0061).
func GuidePath(st *store.Store) string {
	guide := filepath.Join(st.Dir, AgentsFileName)
	if abs, err := filepath.Abs(guide); err == nil {
		return abs
	}
	return filepath.Clean(guide)
}

func writeIfChanged(path string, content []byte) (bool, error) {
	if existing, err := os.ReadFile(path); err == nil && string(existing) == string(content) {
		return false, nil
	} else if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	if err := fsx.WriteAtomic(path, content); err != nil {
		return false, err
	}
	return true, nil
}

// offering is the columns `tq ready` hands work out of, for the guide.
func offering(columns task.Columns) []string {
	var out []string
	for _, name := range columns.Names() {
		if columns.Offers(name) {
			out = append(out, name)
		}
	}
	if len(out) == 0 {
		return []string{"no column"}
	}
	return out
}

// satisfying is the column a dependency has to reach to count as met, or a
// phrase saying the project has not settled on one.
func satisfying(columns task.Columns) string {
	name, err := columns.SatisfyingColumn()
	if err != nil {
		return "no column this project has agreed on"
	}
	return name
}

// taskGuide is the agent-facing cheat sheet stored next to the tasks. It is
// generated so it cannot drift from the statuses, priorities and exit codes the
// binary actually implements.
func taskGuide(taskDir string, priorities task.Priorities, columns task.Columns) []byte {
	// The examples set a priority too, so they have to name one the project
	// actually has: `tq add --priority high` is as much a lie as the list would
	// be. The most severe is always there — Names falls back to the built-in
	// set, and the config loader refuses an empty one.
	example := priorities.Names()[0]

	return fmt.Appendf(nil, `%s

# Task queue

This directory is a `+"`tq`"+` task queue: one Markdown file per task, named
`+"`<id>-<title-slug>.md`"+`, with YAML frontmatter. The files are the source of
truth and are meant to be committed.

Use the CLI rather than editing files by hand — it validates, keeps timestamps
and filenames in sync, and writes atomically. Every command below works from any
subdirectory of the repository.

## Working a task

Claim a task before the first edit and close it before you report the work
done. These are steps in the task, not bookkeeping around it.

1. `+"`tq ready --json`"+` — the tasks that are unblocked and unclaimed.
2. `+"`tq show <id> --json`"+` — read it in full, body included.
3. `+"`tq move <id> in-progress`"+` — claim it, before you touch a file.
4. `+"`tq note <id> \"what happened\"`"+` — append a timestamped note as you go:
   decisions, surprises, anything the next reader would need. A note keeps the
   line breaks you give it, so it can hold a paragraph or a short list.
5. `+"`tq done <id>`"+` — close it once the work is verified.

Use `+"`tq move <id> <status>`"+` for any other transition.

## Find things

    tq list --json                  every task
    tq list --status todo --label backend --priority %s --assignee agent-api
    ls %s | grep auth               filenames carry a slug of the title
    grep -ril "oidc" %s             full-text search across tasks

## Create and change

    tq add "Title" --priority %s --label backend --depends-on TQ-0002 --body "…"

A task filed this way lands in the board's default column, which may not
be one `+"`tq ready`"+` offers — see Statuses below.
`+"`tq move <id> <status>`"+` is what puts it in the queue.
    tq update <id> --title "New title" --assignee agent-api
    tq update <id> --add-label auth --remove-label backend
    tq update <id> --add-dependency TQ-0002 --remove-dependency TQ-0003

Arguments starting with "-" go after "--": tq note <id> -- "-1 test failing".

## Labels

Labels are freeform — `+"`--label`"+` takes any string — but the project declares a
vocabulary in `+"`%s`"+`, and that is the shared one: it is what
gives a label its colour and display name on the board, and what groups it
under the part before a `+"`/`"+`. Prefer a label already in the set. A new one is
accepted everywhere and simply renders neutral, and it shows up as
unconfigured below, so it can be adopted into the set or cleaned up.

    tq label list                   the vocabulary, and what each label is on
    tq label list --json            the same, for an agent

The `+"`/`"+` groups labels for display only. A label is stored and matched as the
whole string, so `+"`tq list --label component/backend`"+` takes the whole key.

## Rules of the format

- Statuses: %s.
  The board, left to right, declared by the project in `+"`%s`"+`: a
  status outside it is refused on write. A task filed without one lands in
  %s. `+"`tq ready`"+` offers work from %s, and a dependency counts as met
  once it reaches %s.
- Priorities: %s (default: %s).
  Most severe first, and that order is the sort order. Unlike labels this is a
  closed set, declared by the project in `+"`%s`"+`: a value outside it
  is refused on write.
- Notes are the last section of a body, introduced by a `+"`---`"+` rule with a blank
  line above it. A `+"`## Notes`"+` heading anywhere else is ordinary content, so a
  body can document notes without `+"`tq note`"+` mistaking prose for notes.
- Each note is one Markdown list item. The lines after its first are indented
  under the bullet, which is what keeps a multi-line note inside its note.
- A task is *ready* when it is neither done nor in-progress and every task in
  `+"`depends_on`"+` exists and is done. A missing dependency blocks it.
- `+"`--json`"+` prints JSON to stdout and nothing else; errors go to stderr.
- Exit codes: 0 success, 1 validation error, 2 task not found, 3 task directory
  missing and uncreatable.

## Where the tasks live

    %s

The project marker is `+"`%s`"+` at the repository root, and it says
where the tasks live:

    version: 1
    path: .tasks

`+"`path`"+` is resolved against the directory holding that file. The marker is
the only thing tq looks for, and the search stops at the repository root: a
directory merely named .tasks is not a queue. The first command that needs one
writes both, so nothing has to be created by hand.

Set `+"`%s`"+` to point tq at a different task directory, which overrides
the marker. Set `+"`%s=true`"+` to let the search walk past the
repository root.
`,
		generatedNotice,
		example,
		filepath.Base(taskDir), filepath.Base(taskDir),
		example,
		config.ConfigFileName,
		strings.Join(columns.Names(), ", "), config.ConfigFileName,
		columns.Default(),
		strings.Join(offering(columns), " and "), satisfying(columns),
		strings.Join(priorities.Names(), ", "), priorities.Default(), config.ConfigFileName,
		taskDir,
		config.ConfigFileName, config.EnvTaskDir, config.EnvWalkForever,
	)
}
