package guide

import (
	"bytes"
	"embed"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/fmartingr/taskqueue/internal/task"

	"github.com/fmartingr/taskqueue/internal/fsx"

	"github.com/fmartingr/taskqueue/internal/config"

	"github.com/fmartingr/taskqueue/internal/store"
)

// AgentsFileName is the guide `tq init` keeps inside the task directory, and
// the file a project's own agent instructions reference.
const AgentsFileName = "AGENTS.md"

// guideTemplateName is the embedded source. It is not AGENTS.md, so an agent
// walking the tree does not take the unfilled template as instructions.
const guideTemplateName = "AGENTS.tmpl.md"

const generatedNotice = "<!-- Generated by `tq init`. Edits are overwritten. -->"

//go:embed AGENTS.tmpl.md
var guideFS embed.FS

// missingkey=error so a renamed field fails the write instead of leaving
// "<no value>" in a file agents will follow.
var guideTmpl = template.Must(template.ParseFS(guideFS, guideTemplateName)).Option("missingkey=error")

// SyncAgentsDocs writes the guide that lives beside the tasks and returns the
// files it wrote, so the CLI can say what changed. It rewrites nothing that is
// already right.
//
// It deliberately does not touch the repository's own AGENTS.md or CLAUDE.md.
// Editing a document tq did not author means parsing arbitrary Markdown, and
// every safe-looking way to do that found another way to damage a committed
// file. Pointing an agent at the guide is one line a person writes once, in the
// file of their choosing; tq prints where the guide is and leaves it to them.
func SyncAgentsDocs(st *store.Store) ([]string, error) {
	// The guide prints the priority vocabulary to agents, so it has to print
	// the project's own or it becomes a lie the moment one is declared.
	priorities, err := st.Priorities()
	if err != nil {
		return nil, err
	}
	columns, err := st.Columns()
	if err != nil {
		return nil, err
	}

	cfg, err := st.Config()
	if err != nil {
		return nil, err
	}

	body, err := taskGuide(cfg.Path, priorities, columns)
	if err != nil {
		return nil, err
	}

	guide := filepath.Join(st.Dir, AgentsFileName)
	// The marker's path is what the project committed; the resolved directory
	// is whoever last ran init's checkout, and a guide that embeds it will
	// not match on any other machine (TQ-0089).
	changed, err := writeIfChanged(guide, body)
	if err != nil {
		return nil, err
	}
	if !changed {
		return nil, nil
	}
	return []string{guide}, nil
}

// GuidePath is the guide's location, for the CLI to name once init has written
// it. It is absolute: the file a user references it from is theirs to choose,
// and no directory this package could pick — the repository root, the parent of
// the task directory, the working directory — is the one that file sits in. A
// relative path would be correct from exactly one of them and silently wrong
// everywhere else (TQ-0061).
func GuidePath(st *store.Store) string {
	guide := filepath.Join(st.Dir, AgentsFileName)
	if abs, err := filepath.Abs(guide); err == nil {
		return abs
	}
	return filepath.Clean(guide)
}

func writeIfChanged(path string, content []byte) (bool, error) {
	if existing, err := os.ReadFile(path); err == nil && string(existing) == string(content) {
		return false, nil
	} else if err != nil && !os.IsNotExist(err) {
		return false, err
	}
	if err := fsx.WriteAtomic(path, content); err != nil {
		return false, err
	}
	return true, nil
}

// offering is the columns `tq ready` hands work out of, for the guide.
func offering(columns task.Columns) []string {
	var out []string
	for _, name := range columns.Names() {
		if columns.Offers(name) {
			out = append(out, name)
		}
	}
	if len(out) == 0 {
		return []string{"no column"}
	}
	return out
}

// satisfying is the column a dependency has to reach to count as met, or a
// phrase saying the project has not settled on one.
func satisfying(columns task.Columns) string {
	name, err := columns.SatisfyingColumn()
	if err != nil {
		return "no column this project has agreed on"
	}
	return name
}

// guideData is what the embedded template fills in from the project's marker:
// the vocabulary, the board, and the path the marker stores.
type guideData struct {
	ExamplePriority string
	TaskDir         string
	ConfigFile      string
	Statuses        string
	DefaultStatus   string
	Offering        string
	Satisfying      string
	Priorities      string
	DefaultPriority string
	EnvConfigPath   string
}

// taskGuide is the agent-facing cheat sheet stored next to the tasks. It is
// generated so it cannot drift from the statuses, priorities and exit codes the
// binary actually implements. The prose lives in AGENTS.tmpl.md beside this
// file; this only fills the values that come from the project's marker.
//
// taskDir is the marker's `path` — the string `.taskqueue.yaml` stores — not
// the resolved absolute directory. The guide is committed, so a checkout path
// would be one machine's home directory.
func taskGuide(taskDir string, priorities task.Priorities, columns task.Columns) ([]byte, error) {
	// The examples set a priority too, so they have to name one the project
	// actually has: `tq add --priority high` is as much a lie as the list would
	// be. The most severe is always there — Names falls back to the built-in
	// set, and the config loader refuses an empty one.
	data := guideData{
		ExamplePriority: priorities.Names()[0],
		TaskDir:         taskDir,
		ConfigFile:      config.ConfigFileName,
		Statuses:        strings.Join(columns.Names(), ", "),
		DefaultStatus:   columns.Default(),
		Offering:        strings.Join(offering(columns), " and "),
		Satisfying:      satisfying(columns),
		Priorities:      strings.Join(priorities.Names(), ", "),
		DefaultPriority: priorities.Default(),
		EnvConfigPath:   config.EnvConfigPath,
	}
	var buf bytes.Buffer
	if err := guideTmpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
